### ISSUE TITLE
SQLite Integrity on Quiz Selector Re-Usage

### ISSUE THREAD

**Issue by Ashthetik** [JohannesNicholas/RoboJoey#3]
Through a bit of playing around I found that there was a lack of safe-guards (didn't occur to me during some restructuring) with the `/quiz` application command.

If a user was to select one answer then try again, afterwards, the bot will throw a non-critical error:
```py
sqlite3.IntegrityError: UNIQUE constraint failed: quiz_selections.quiz_id, quiz_selections.user_id
```

Whilst this might not be critical to the bot's performance, it would be worth adding in a check to prevent log-abuse

**Comment by JohannesNicholas** [comment]
Thank you for debugging!
This issue has been known about but the latest 2 commit has added a guard to prevent it: (https://github.com/JohannesNicholas/RoboJoey/commit/07287e7af75b6923d5c71286aa4b3628db40eca6)
